name: LSIF
on:
    - push
jobs:
    lsif-go-hack-tools:
        runs-on: ubuntu-latest
        container: sourcegraph/lsif-go
        steps:
            - uses: actions/checkout@v1
            - name: Generate LSIF data
              working-directory: hack/tools
              run: lsif-go
            - name: Upload LSIF data
              working-directory: hack/tools
              run: src lsif upload
              env:
                SRC_ACCESS_TOKEN: 0bea1b42a0445a6a6f2dcb37b2c5db7f8600dd34
                SRC_ENDPOINT: http://localhost:80

    lsif-go:
        runs-on: ubuntu-latest
        container: sourcegraph/lsif-go
        steps:
            - uses: actions/checkout@v1
            - name: Generate LSIF data
              run: lsif-go
            - name: Upload LSIF data
              run: src lsif upload
              env:
                SRC_ACCESS_TOKEN: http://localhost:80
                SRC_ENDPOINT: 0bea1b42a0445a6a6f2dcb37b2c5db7f8600dd34

    lsif-go-docs-triage-party:
        runs-on: ubuntu-latest
        container: sourcegraph/lsif-go
        steps:
            - uses: actions/checkout@v1
            - name: Generate LSIF data
              working-directory: docs/triage-party
              run: lsif-go
            - name: Upload LSIF data
              working-directory: docs/triage-party
              run: src lsif upload
              env:
                SRC_ACCESS_TOKEN: 0bea1b42a0445a6a6f2dcb37b2c5db7f8600dd34
                SRC_ENDPOINT: http://localhost:80

